version: '3.8'

networks:
  spring-net:

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:7
    command: --port 6379
    ports:
      - "6379:6379"
    networks:
      - spring-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8099:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - spring-net